# Cloudflare Workers configuration
# See: https://developers.cloudflare.com/workers/configuration/

name = "nuywznihg08edfslfk29"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# These should be configured with: wrangler secret put SECRET_NAME
# Example secrets for the routing.json configuration:
# - 6nr8n2i1ve1rdnku8d1t (HubSpot API key)
# - fhwowggbohorrud2kj16 (Notion API key)

# KV namespace bindings
# [[kv_namespaces]]
# binding = "CF_STATE"
# id = ""  # Will be populated from CF_IaC terraform outputs
# Uncomment and add KV namespace ID when available

# Durable Object bindings (if needed)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# R2 bucket bindings (if needed)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Routes for deployment
routes = ["api.simplesalt.company/nuywznihg08edfslfk29"]

# Build configuration
# [build]
# command = "npm run build"

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

# Staging configuration  
[env.staging]
vars = { ENVIRONMENT = "staging" }